packages:
  - "apps/*"
  - "packages/*"

catalog:
  zod: "4.2.1"
  effect: "latest"
  "@effect/rpc": "latest"
  "@effect/schema": "latest"
  "@effect/platform": "latest"
  "@effect/platform-node": "latest"
  "@effect/cluster": "latest"
  "@effect/sql": "latest"
  "@effect/experimental": "latest"
  pino: "9.6.0"
  better-auth: "^1.4.18"
  drizzle-orm: "^0.45.1"
  postgres: "^3.4.8"
  bcryptjs: "^3.0.3"

overrides:
  zod: "catalog:"
