packages:
  - "apps/*"
  - "packages/*"

catalog:
  zod: "4.2.1"
  effect: "^3.19.15"
  "@effect/rpc": "^0.73.0"
  "@effect/schema": "^0.75.5"
  "@effect/platform": "^0.94.2"
  "@effect/platform-node": "^0.104.1"
  "@effect/cluster": "^0.56.1"
  "@effect/sql": "^0.49.0"
  "@effect/experimental": "^0.58.0"
  pino: "9.6.0"
  better-auth: "^1.4.18"
  drizzle-orm: "^0.45.1"
  postgres: "^3.4.8"
  bcryptjs: "^3.0.3"

overrides:
  zod: "catalog:"
