/**
 * Archetype Types for OCEAN Personality Code System
 *
 * Maps 4-letter OCEAN codes (O,C,E,A trait levels) to memorable personality archetypes.
 * Each trait uses unique, semantically meaningful letters instead of generic L/M/H:
 *
 * Openness:          T (Traditional)   M (Moderate)     O (Open-minded)
 * Conscientiousness:  F (Flexible)      S (Steady)       C (Conscientious)
 * Extraversion:       I (Introverted)   B (Balanced)     E (Extravert)
 * Agreeableness:      D (Direct)        P (Pragmatic)    A (Agreeable)
 * Neuroticism:        R (Resilient)     V (Variable)     N (Neurotic)
 *
 * Full 5-letter codes (including Neuroticism) are stored but only 4 letters are used
 * for archetype naming in POC. Phase 2 will extend to all 5 traits (243 combinations).
 */

import type { Schema } from "effect";
import type { TraitName } from "../constants/big-five";
import type { OceanCode4Schema, OceanCode5Schema } from "../schemas/ocean-code";

/** Openness level letters */
export type OpennessLevel = "T" | "M" | "O";
/** Conscientiousness level letters */
export type ConscientiousnessLevel = "F" | "S" | "C";
/** Extraversion level letters */
export type ExtraversionLevel = "I" | "B" | "E";
/** Agreeableness level letters */
export type AgreeablenessLevel = "D" | "P" | "A";
/** Neuroticism level letters */
export type NeuroticismLevel = "R" | "V" | "N";

/** Union of all possible trait-level letters */
export type TraitLevel =
	| OpennessLevel
	| ConscientiousnessLevel
	| ExtraversionLevel
	| AgreeablenessLevel
	| NeuroticismLevel;

/** 4-letter OCEAN code — branded string inferred from schema (e.g., "OCEA") */
export type OceanCode4 = Schema.Schema.Type<typeof OceanCode4Schema>;

/** 5-letter OCEAN code — branded string inferred from schema (e.g., "OCEAR") */
export type OceanCode5 = Schema.Schema.Type<typeof OceanCode5Schema>;

/** Trait-specific letter mapping: [Low, Mid, High] per trait */
export const TRAIT_LETTER_MAP: Record<TraitName, readonly [string, string, string]> = {
	openness: ["T", "M", "O"],
	conscientiousness: ["F", "S", "C"],
	extraversion: ["I", "B", "E"],
	agreeableness: ["D", "P", "A"],
	neuroticism: ["R", "V", "N"],
} as const;

/** Human-readable label for each trait-level letter, keyed by trait then letter */
export const TRAIT_LEVEL_LABELS: Record<TraitName, Record<string, string>> = {
	openness: { T: "Traditional", M: "Moderate", O: "Open-minded" },
	conscientiousness: { F: "Flexible", S: "Steady", C: "Conscientious" },
	extraversion: { I: "Introverted", B: "Balanced", E: "Extravert" },
	agreeableness: { D: "Direct", P: "Pragmatic", A: "Agreeable" },
	neuroticism: { R: "Resilient", V: "Variable", N: "Neurotic" },
} as const;

/** Resolve a trait-level letter to its human-readable label */
export const getTraitLevelLabel = (trait: TraitName, letter: string): string =>
	TRAIT_LEVEL_LABELS[trait][letter] ?? letter;

/**
 * Personality archetype derived from a 4-letter OCEAN code.
 *
 * @example
 * ```typescript
 * const archetype: Archetype = {
 *   code4: "OCBA",
 *   name: "Creative Diplomat",
 *   description: "Open-minded and organized with a reserved nature...",
 *   color: "#4A90D9",
 *   isCurated: true,
 * }
 * ```
 */
export interface Archetype {
	/** 4-letter lookup key (O, C, E, A levels) */
	readonly code4: OceanCode4;
	/** Memorable personality name (e.g., "Thoughtful Collaborator") */
	readonly name: string;
	/** Rich description (1500-2500 characters) explaining the trait combination */
	readonly description: string;
	/** Hex color code for visual representation (e.g., "#4A90D9") */
	readonly color: string;
	/** Whether this archetype was hand-curated (true) or generated by fallback (false) */
	readonly isCurated: boolean;
}
