/**
 * Archetype Types for OCEAN Personality Code System
 *
 * Maps 4-letter OCEAN codes (O,C,E,A trait levels) to memorable personality archetypes.
 * Each trait is classified as Low (L), Mid (M), or High (H), producing 81 combinations (3^4).
 *
 * Full 5-letter codes (including Neuroticism) are stored but only 4 letters are used
 * for archetype naming in POC. Phase 2 will extend to all 5 traits (243 combinations).
 */

/** Trait level classification: Low, Mid, or High */
export type TraitLevel = "L" | "M" | "H";

/** 4-letter OCEAN code using O, C, E, A traits (e.g., "HMLH") */
export type OceanCode4 = `${TraitLevel}${TraitLevel}${TraitLevel}${TraitLevel}`;

/** 5-letter OCEAN code using all 5 traits (e.g., "HMLHM") */
export type OceanCode5 = `${TraitLevel}${TraitLevel}${TraitLevel}${TraitLevel}${TraitLevel}`;

/**
 * Personality archetype derived from a 4-letter OCEAN code.
 *
 * @example
 * ```typescript
 * const archetype: Archetype = {
 *   code4: "HHMH",
 *   name: "Creative Diplomat",
 *   description: "Open-minded and organized with a reserved nature...",
 *   color: "#4A90D9",
 *   isCurated: true,
 * }
 * ```
 */
export interface Archetype {
	/** 4-letter lookup key (O, C, E, A levels) */
	readonly code4: OceanCode4;
	/** Memorable personality name (e.g., "Thoughtful Collaborator") */
	readonly name: string;
	/** 2-3 sentence description explaining the trait combination */
	readonly description: string;
	/** Hex color code for visual representation (e.g., "#4A90D9") */
	readonly color: string;
	/** Whether this archetype was hand-curated (true) or generated by fallback (false) */
	readonly isCurated: boolean;
}
