/**
 * Archetype Types for OCEAN Personality Code System
 *
 * Maps 4-letter OCEAN codes (O,C,E,A trait levels) to memorable personality archetypes.
 * Each trait uses unique, semantically meaningful letters instead of generic L/M/H:
 *
 * Openness:          P (Practical)     G (Grounded)     O (Open-minded)
 * Conscientiousness:  F (Flexible)      B (Balanced)     D (Disciplined)
 * Extraversion:       I (Introvert)     A (Ambivert)     E (Extravert)
 * Agreeableness:      C (Candid)        N (Negotiator)   W (Warm)
 * Neuroticism:        R (Resilient)     T (Temperate)    S (Sensitive)
 *
 * Full 5-letter codes (including Neuroticism) are stored but only 4 letters are used
 * for archetype naming in POC. Phase 2 will extend to all 5 traits (243 combinations).
 */

import type { Schema } from "effect";
import type { TraitName } from "../constants/big-five";
import type { OceanCode4Schema, OceanCode5Schema } from "../schemas/ocean-code";

/** Openness level letters */
export type OpennessLevel = "P" | "G" | "O";
/** Conscientiousness level letters */
export type ConscientiousnessLevel = "F" | "B" | "D";
/** Extraversion level letters */
export type ExtraversionLevel = "I" | "A" | "E";
/** Agreeableness level letters */
export type AgreeablenessLevel = "C" | "N" | "W";
/** Neuroticism level letters */
export type NeuroticismLevel = "R" | "T" | "S";

/** Union of all possible trait-level letters */
export type TraitLevel =
	| OpennessLevel
	| ConscientiousnessLevel
	| ExtraversionLevel
	| AgreeablenessLevel
	| NeuroticismLevel;

/** 4-letter OCEAN code — branded string inferred from schema (e.g., "ODEW") */
export type OceanCode4 = Schema.Schema.Type<typeof OceanCode4Schema>;

/** 5-letter OCEAN code — branded string inferred from schema (e.g., "ODEWR") */
export type OceanCode5 = Schema.Schema.Type<typeof OceanCode5Schema>;

/** Trait-specific letter mapping: [Low, Mid, High] per trait */
export const TRAIT_LETTER_MAP: Record<TraitName, readonly [string, string, string]> = {
	openness: ["P", "G", "O"],
	conscientiousness: ["F", "B", "D"],
	extraversion: ["I", "A", "E"],
	agreeableness: ["C", "N", "W"],
	neuroticism: ["R", "T", "S"],
} as const;

/** Human-readable label for each trait-level letter */
export const TRAIT_LEVEL_LABELS: Record<string, string> = {
	// Openness
	P: "Practical",
	G: "Grounded",
	O: "Open-minded",
	// Conscientiousness
	F: "Flexible",
	B: "Balanced",
	D: "Disciplined",
	// Extraversion
	I: "Introvert",
	A: "Ambivert",
	E: "Extravert",
	// Agreeableness
	C: "Candid",
	N: "Negotiator",
	W: "Warm",
	// Neuroticism
	R: "Resilient",
	T: "Temperate",
	S: "Sensitive",
} as const;

/**
 * Personality archetype derived from a 4-letter OCEAN code.
 *
 * @example
 * ```typescript
 * const archetype: Archetype = {
 *   code4: "ODAW",
 *   name: "Creative Diplomat",
 *   description: "Open-minded and organized with a reserved nature...",
 *   color: "#4A90D9",
 *   isCurated: true,
 * }
 * ```
 */
export interface Archetype {
	/** 4-letter lookup key (O, C, E, A levels) */
	readonly code4: OceanCode4;
	/** Memorable personality name (e.g., "Thoughtful Collaborator") */
	readonly name: string;
	/** 2-3 sentence description explaining the trait combination */
	readonly description: string;
	/** Hex color code for visual representation (e.g., "#4A90D9") */
	readonly color: string;
	/** Whether this archetype was hand-curated (true) or generated by fallback (false) */
	readonly isCurated: boolean;
}
