/**
 * HTTP API Error Classes
 *
 * Re-exported from @workspace/domain where they are canonically defined.
 * Contracts consumers can continue importing from "@workspace/contracts" or "@workspace/contracts/errors".
 */

export {
	AccountNotFound,
	AgentInvocationError,
	AnalyzerError,
	AssessmentNotCompletedError,
	AssessmentResultsNotReady,
	ConcurrentMessageError,
	ConversationAlreadyExists,
	ConversationEvidenceError,
	CostLimitExceeded,
	DatabaseError,
	FeatureUnavailable,
	FinalizationInProgressError,
	FreeTierLimitReached,
	GlobalAssessmentLimitReached,
	InsufficientCreditsError,
	InvalidCredentials,
	InvalidFacetNameError,
	InvalidYearMonthError,
	InvitationAlreadyRespondedError,
	InvitationNotFoundError,
	MalformedEvidenceError,
	MessageRateLimitError,
	NerinError,
	ProfileError,
	ProfileNotFound,
	ProfilePrivate,
	PublicProfileNotProvisioned,
	QrTokenAlreadyAcceptedError,
	QrTokenExpiredError,
	QrTokenNotFoundError,
	RateLimitExceeded,
	RelationshipAnalysisNotFoundError,
	RelationshipAnalysisUnauthorizedError,
	RelationshipSharedNoteValidationError,
	SelfInvitationError,
	SessionCompletedError,
	SessionExpired,
	SessionNotCompleted,
	SessionNotFinalizing,
	SessionNotFound,
	SubscriptionRequired,
	Unauthorized,
	UnknownProductError,
	UserAlreadyExists,
	WebhookVerificationError,
	WeeklyLetterNotFound,
} from "@workspace/domain";
