/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VerifyEmailRouteImport } from './routes/verify-email'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TodayIndexRouteImport } from './routes/today/index'
import { Route as MeIndexRouteImport } from './routes/me/index'
import { Route as LibraryIndexRouteImport } from './routes/library/index'
import { Route as CircleIndexRouteImport } from './routes/circle/index'
import { Route as ChatIndexRouteImport } from './routes/chat/index'
import { Route as TodayCalendarRouteImport } from './routes/today/calendar'
import { Route as RelationshipAnalysisIdRouteImport } from './routes/relationship/$analysisId'
import { Route as PublicProfilePublicProfileIdRouteImport } from './routes/public-profile.$publicProfileId'
import { Route as MeConversationSessionIdRouteImport } from './routes/me/$conversationSessionId'
import { Route as DevEmailsRouteImport } from './routes/dev/emails'
import { Route as DevComponentsRouteImport } from './routes/dev/components'
import { Route as TodayWeekWeekIdRouteImport } from './routes/today/week.$weekId'
import { Route as RelationshipQrTokenRouteImport } from './routes/relationship/qr/$token'
import { Route as RelationshipAnalysisIdRitualRouteImport } from './routes/relationship/$analysisId_.ritual'
import { Route as LibraryTraitSlugRouteImport } from './routes/library/trait.$slug'
import { Route as LibraryScienceSlugRouteImport } from './routes/library/science.$slug'
import { Route as LibraryGuidesSlugRouteImport } from './routes/library/guides.$slug'
import { Route as LibraryFacetSlugRouteImport } from './routes/library/facet.$slug'
import { Route as LibraryArchetypeSlugRouteImport } from './routes/library/archetype.$slug'
import { Route as DevLibraryOpusRedesign3RouteImport } from './routes/dev/library/opus/redesign-3'
import { Route as DevLibraryOpusRedesign2RouteImport } from './routes/dev/library/opus/redesign-2'
import { Route as DevLibraryOpusRedesign1RouteImport } from './routes/dev/library/opus/redesign-1'
import { Route as DevLibraryGptRedesign3RouteImport } from './routes/dev/library/gpt/redesign-3'
import { Route as DevLibraryGptRedesign2RouteImport } from './routes/dev/library/gpt/redesign-2'
import { Route as DevLibraryGptRedesign1RouteImport } from './routes/dev/library/gpt/redesign-1'
import { Route as DevLibraryDirectionTraitRouteImport } from './routes/dev/library/direction/trait'
import { Route as DevLibraryDirectionFacetRouteImport } from './routes/dev/library/direction/facet'
import { Route as DevLibraryDirectionArchetypeRouteImport } from './routes/dev/library/direction/archetype'
import { Route as DevLibraryComposerRedesign3RouteImport } from './routes/dev/library/composer/redesign-3'
import { Route as DevLibraryComposerRedesign2RouteImport } from './routes/dev/library/composer/redesign-2'
import { Route as DevLibraryComposerRedesign1RouteImport } from './routes/dev/library/composer/redesign-1'

const VerifyEmailRoute = VerifyEmailRouteImport.update({
  id: '/verify-email',
  path: '/verify-email',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TodayIndexRoute = TodayIndexRouteImport.update({
  id: '/today/',
  path: '/today/',
  getParentRoute: () => rootRouteImport,
} as any)
const MeIndexRoute = MeIndexRouteImport.update({
  id: '/me/',
  path: '/me/',
  getParentRoute: () => rootRouteImport,
} as any)
const LibraryIndexRoute = LibraryIndexRouteImport.update({
  id: '/library/',
  path: '/library/',
  getParentRoute: () => rootRouteImport,
} as any)
const CircleIndexRoute = CircleIndexRouteImport.update({
  id: '/circle/',
  path: '/circle/',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatIndexRoute = ChatIndexRouteImport.update({
  id: '/chat/',
  path: '/chat/',
  getParentRoute: () => rootRouteImport,
} as any)
const TodayCalendarRoute = TodayCalendarRouteImport.update({
  id: '/today/calendar',
  path: '/today/calendar',
  getParentRoute: () => rootRouteImport,
} as any)
const RelationshipAnalysisIdRoute = RelationshipAnalysisIdRouteImport.update({
  id: '/relationship/$analysisId',
  path: '/relationship/$analysisId',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicProfilePublicProfileIdRoute =
  PublicProfilePublicProfileIdRouteImport.update({
    id: '/public-profile/$publicProfileId',
    path: '/public-profile/$publicProfileId',
    getParentRoute: () => rootRouteImport,
  } as any)
const MeConversationSessionIdRoute = MeConversationSessionIdRouteImport.update({
  id: '/me/$conversationSessionId',
  path: '/me/$conversationSessionId',
  getParentRoute: () => rootRouteImport,
} as any)
const DevEmailsRoute = DevEmailsRouteImport.update({
  id: '/dev/emails',
  path: '/dev/emails',
  getParentRoute: () => rootRouteImport,
} as any)
const DevComponentsRoute = DevComponentsRouteImport.update({
  id: '/dev/components',
  path: '/dev/components',
  getParentRoute: () => rootRouteImport,
} as any)
const TodayWeekWeekIdRoute = TodayWeekWeekIdRouteImport.update({
  id: '/today/week/$weekId',
  path: '/today/week/$weekId',
  getParentRoute: () => rootRouteImport,
} as any)
const RelationshipQrTokenRoute = RelationshipQrTokenRouteImport.update({
  id: '/relationship/qr/$token',
  path: '/relationship/qr/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const RelationshipAnalysisIdRitualRoute =
  RelationshipAnalysisIdRitualRouteImport.update({
    id: '/relationship/$analysisId_/ritual',
    path: '/relationship/$analysisId/ritual',
    getParentRoute: () => rootRouteImport,
  } as any)
const LibraryTraitSlugRoute = LibraryTraitSlugRouteImport.update({
  id: '/library/trait/$slug',
  path: '/library/trait/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const LibraryScienceSlugRoute = LibraryScienceSlugRouteImport.update({
  id: '/library/science/$slug',
  path: '/library/science/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const LibraryGuidesSlugRoute = LibraryGuidesSlugRouteImport.update({
  id: '/library/guides/$slug',
  path: '/library/guides/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const LibraryFacetSlugRoute = LibraryFacetSlugRouteImport.update({
  id: '/library/facet/$slug',
  path: '/library/facet/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const LibraryArchetypeSlugRoute = LibraryArchetypeSlugRouteImport.update({
  id: '/library/archetype/$slug',
  path: '/library/archetype/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const DevLibraryOpusRedesign3Route = DevLibraryOpusRedesign3RouteImport.update({
  id: '/dev/library/opus/redesign-3',
  path: '/dev/library/opus/redesign-3',
  getParentRoute: () => rootRouteImport,
} as any)
const DevLibraryOpusRedesign2Route = DevLibraryOpusRedesign2RouteImport.update({
  id: '/dev/library/opus/redesign-2',
  path: '/dev/library/opus/redesign-2',
  getParentRoute: () => rootRouteImport,
} as any)
const DevLibraryOpusRedesign1Route = DevLibraryOpusRedesign1RouteImport.update({
  id: '/dev/library/opus/redesign-1',
  path: '/dev/library/opus/redesign-1',
  getParentRoute: () => rootRouteImport,
} as any)
const DevLibraryGptRedesign3Route = DevLibraryGptRedesign3RouteImport.update({
  id: '/dev/library/gpt/redesign-3',
  path: '/dev/library/gpt/redesign-3',
  getParentRoute: () => rootRouteImport,
} as any)
const DevLibraryGptRedesign2Route = DevLibraryGptRedesign2RouteImport.update({
  id: '/dev/library/gpt/redesign-2',
  path: '/dev/library/gpt/redesign-2',
  getParentRoute: () => rootRouteImport,
} as any)
const DevLibraryGptRedesign1Route = DevLibraryGptRedesign1RouteImport.update({
  id: '/dev/library/gpt/redesign-1',
  path: '/dev/library/gpt/redesign-1',
  getParentRoute: () => rootRouteImport,
} as any)
const DevLibraryDirectionTraitRoute =
  DevLibraryDirectionTraitRouteImport.update({
    id: '/dev/library/direction/trait',
    path: '/dev/library/direction/trait',
    getParentRoute: () => rootRouteImport,
  } as any)
const DevLibraryDirectionFacetRoute =
  DevLibraryDirectionFacetRouteImport.update({
    id: '/dev/library/direction/facet',
    path: '/dev/library/direction/facet',
    getParentRoute: () => rootRouteImport,
  } as any)
const DevLibraryDirectionArchetypeRoute =
  DevLibraryDirectionArchetypeRouteImport.update({
    id: '/dev/library/direction/archetype',
    path: '/dev/library/direction/archetype',
    getParentRoute: () => rootRouteImport,
  } as any)
const DevLibraryComposerRedesign3Route =
  DevLibraryComposerRedesign3RouteImport.update({
    id: '/dev/library/composer/redesign-3',
    path: '/dev/library/composer/redesign-3',
    getParentRoute: () => rootRouteImport,
  } as any)
const DevLibraryComposerRedesign2Route =
  DevLibraryComposerRedesign2RouteImport.update({
    id: '/dev/library/composer/redesign-2',
    path: '/dev/library/composer/redesign-2',
    getParentRoute: () => rootRouteImport,
  } as any)
const DevLibraryComposerRedesign1Route =
  DevLibraryComposerRedesign1RouteImport.update({
    id: '/dev/library/composer/redesign-1',
    path: '/dev/library/composer/redesign-1',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/settings': typeof SettingsRoute
  '/signup': typeof SignupRoute
  '/verify-email': typeof VerifyEmailRoute
  '/dev/components': typeof DevComponentsRoute
  '/dev/emails': typeof DevEmailsRoute
  '/me/$conversationSessionId': typeof MeConversationSessionIdRoute
  '/public-profile/$publicProfileId': typeof PublicProfilePublicProfileIdRoute
  '/relationship/$analysisId': typeof RelationshipAnalysisIdRoute
  '/today/calendar': typeof TodayCalendarRoute
  '/chat/': typeof ChatIndexRoute
  '/circle/': typeof CircleIndexRoute
  '/library/': typeof LibraryIndexRoute
  '/me/': typeof MeIndexRoute
  '/today/': typeof TodayIndexRoute
  '/library/archetype/$slug': typeof LibraryArchetypeSlugRoute
  '/library/facet/$slug': typeof LibraryFacetSlugRoute
  '/library/guides/$slug': typeof LibraryGuidesSlugRoute
  '/library/science/$slug': typeof LibraryScienceSlugRoute
  '/library/trait/$slug': typeof LibraryTraitSlugRoute
  '/relationship/$analysisId/ritual': typeof RelationshipAnalysisIdRitualRoute
  '/relationship/qr/$token': typeof RelationshipQrTokenRoute
  '/today/week/$weekId': typeof TodayWeekWeekIdRoute
  '/dev/library/composer/redesign-1': typeof DevLibraryComposerRedesign1Route
  '/dev/library/composer/redesign-2': typeof DevLibraryComposerRedesign2Route
  '/dev/library/composer/redesign-3': typeof DevLibraryComposerRedesign3Route
  '/dev/library/direction/archetype': typeof DevLibraryDirectionArchetypeRoute
  '/dev/library/direction/facet': typeof DevLibraryDirectionFacetRoute
  '/dev/library/direction/trait': typeof DevLibraryDirectionTraitRoute
  '/dev/library/gpt/redesign-1': typeof DevLibraryGptRedesign1Route
  '/dev/library/gpt/redesign-2': typeof DevLibraryGptRedesign2Route
  '/dev/library/gpt/redesign-3': typeof DevLibraryGptRedesign3Route
  '/dev/library/opus/redesign-1': typeof DevLibraryOpusRedesign1Route
  '/dev/library/opus/redesign-2': typeof DevLibraryOpusRedesign2Route
  '/dev/library/opus/redesign-3': typeof DevLibraryOpusRedesign3Route
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/settings': typeof SettingsRoute
  '/signup': typeof SignupRoute
  '/verify-email': typeof VerifyEmailRoute
  '/dev/components': typeof DevComponentsRoute
  '/dev/emails': typeof DevEmailsRoute
  '/me/$conversationSessionId': typeof MeConversationSessionIdRoute
  '/public-profile/$publicProfileId': typeof PublicProfilePublicProfileIdRoute
  '/relationship/$analysisId': typeof RelationshipAnalysisIdRoute
  '/today/calendar': typeof TodayCalendarRoute
  '/chat': typeof ChatIndexRoute
  '/circle': typeof CircleIndexRoute
  '/library': typeof LibraryIndexRoute
  '/me': typeof MeIndexRoute
  '/today': typeof TodayIndexRoute
  '/library/archetype/$slug': typeof LibraryArchetypeSlugRoute
  '/library/facet/$slug': typeof LibraryFacetSlugRoute
  '/library/guides/$slug': typeof LibraryGuidesSlugRoute
  '/library/science/$slug': typeof LibraryScienceSlugRoute
  '/library/trait/$slug': typeof LibraryTraitSlugRoute
  '/relationship/$analysisId/ritual': typeof RelationshipAnalysisIdRitualRoute
  '/relationship/qr/$token': typeof RelationshipQrTokenRoute
  '/today/week/$weekId': typeof TodayWeekWeekIdRoute
  '/dev/library/composer/redesign-1': typeof DevLibraryComposerRedesign1Route
  '/dev/library/composer/redesign-2': typeof DevLibraryComposerRedesign2Route
  '/dev/library/composer/redesign-3': typeof DevLibraryComposerRedesign3Route
  '/dev/library/direction/archetype': typeof DevLibraryDirectionArchetypeRoute
  '/dev/library/direction/facet': typeof DevLibraryDirectionFacetRoute
  '/dev/library/direction/trait': typeof DevLibraryDirectionTraitRoute
  '/dev/library/gpt/redesign-1': typeof DevLibraryGptRedesign1Route
  '/dev/library/gpt/redesign-2': typeof DevLibraryGptRedesign2Route
  '/dev/library/gpt/redesign-3': typeof DevLibraryGptRedesign3Route
  '/dev/library/opus/redesign-1': typeof DevLibraryOpusRedesign1Route
  '/dev/library/opus/redesign-2': typeof DevLibraryOpusRedesign2Route
  '/dev/library/opus/redesign-3': typeof DevLibraryOpusRedesign3Route
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/settings': typeof SettingsRoute
  '/signup': typeof SignupRoute
  '/verify-email': typeof VerifyEmailRoute
  '/dev/components': typeof DevComponentsRoute
  '/dev/emails': typeof DevEmailsRoute
  '/me/$conversationSessionId': typeof MeConversationSessionIdRoute
  '/public-profile/$publicProfileId': typeof PublicProfilePublicProfileIdRoute
  '/relationship/$analysisId': typeof RelationshipAnalysisIdRoute
  '/today/calendar': typeof TodayCalendarRoute
  '/chat/': typeof ChatIndexRoute
  '/circle/': typeof CircleIndexRoute
  '/library/': typeof LibraryIndexRoute
  '/me/': typeof MeIndexRoute
  '/today/': typeof TodayIndexRoute
  '/library/archetype/$slug': typeof LibraryArchetypeSlugRoute
  '/library/facet/$slug': typeof LibraryFacetSlugRoute
  '/library/guides/$slug': typeof LibraryGuidesSlugRoute
  '/library/science/$slug': typeof LibraryScienceSlugRoute
  '/library/trait/$slug': typeof LibraryTraitSlugRoute
  '/relationship/$analysisId_/ritual': typeof RelationshipAnalysisIdRitualRoute
  '/relationship/qr/$token': typeof RelationshipQrTokenRoute
  '/today/week/$weekId': typeof TodayWeekWeekIdRoute
  '/dev/library/composer/redesign-1': typeof DevLibraryComposerRedesign1Route
  '/dev/library/composer/redesign-2': typeof DevLibraryComposerRedesign2Route
  '/dev/library/composer/redesign-3': typeof DevLibraryComposerRedesign3Route
  '/dev/library/direction/archetype': typeof DevLibraryDirectionArchetypeRoute
  '/dev/library/direction/facet': typeof DevLibraryDirectionFacetRoute
  '/dev/library/direction/trait': typeof DevLibraryDirectionTraitRoute
  '/dev/library/gpt/redesign-1': typeof DevLibraryGptRedesign1Route
  '/dev/library/gpt/redesign-2': typeof DevLibraryGptRedesign2Route
  '/dev/library/gpt/redesign-3': typeof DevLibraryGptRedesign3Route
  '/dev/library/opus/redesign-1': typeof DevLibraryOpusRedesign1Route
  '/dev/library/opus/redesign-2': typeof DevLibraryOpusRedesign2Route
  '/dev/library/opus/redesign-3': typeof DevLibraryOpusRedesign3Route
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/settings'
    | '/signup'
    | '/verify-email'
    | '/dev/components'
    | '/dev/emails'
    | '/me/$conversationSessionId'
    | '/public-profile/$publicProfileId'
    | '/relationship/$analysisId'
    | '/today/calendar'
    | '/chat/'
    | '/circle/'
    | '/library/'
    | '/me/'
    | '/today/'
    | '/library/archetype/$slug'
    | '/library/facet/$slug'
    | '/library/guides/$slug'
    | '/library/science/$slug'
    | '/library/trait/$slug'
    | '/relationship/$analysisId/ritual'
    | '/relationship/qr/$token'
    | '/today/week/$weekId'
    | '/dev/library/composer/redesign-1'
    | '/dev/library/composer/redesign-2'
    | '/dev/library/composer/redesign-3'
    | '/dev/library/direction/archetype'
    | '/dev/library/direction/facet'
    | '/dev/library/direction/trait'
    | '/dev/library/gpt/redesign-1'
    | '/dev/library/gpt/redesign-2'
    | '/dev/library/gpt/redesign-3'
    | '/dev/library/opus/redesign-1'
    | '/dev/library/opus/redesign-2'
    | '/dev/library/opus/redesign-3'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/settings'
    | '/signup'
    | '/verify-email'
    | '/dev/components'
    | '/dev/emails'
    | '/me/$conversationSessionId'
    | '/public-profile/$publicProfileId'
    | '/relationship/$analysisId'
    | '/today/calendar'
    | '/chat'
    | '/circle'
    | '/library'
    | '/me'
    | '/today'
    | '/library/archetype/$slug'
    | '/library/facet/$slug'
    | '/library/guides/$slug'
    | '/library/science/$slug'
    | '/library/trait/$slug'
    | '/relationship/$analysisId/ritual'
    | '/relationship/qr/$token'
    | '/today/week/$weekId'
    | '/dev/library/composer/redesign-1'
    | '/dev/library/composer/redesign-2'
    | '/dev/library/composer/redesign-3'
    | '/dev/library/direction/archetype'
    | '/dev/library/direction/facet'
    | '/dev/library/direction/trait'
    | '/dev/library/gpt/redesign-1'
    | '/dev/library/gpt/redesign-2'
    | '/dev/library/gpt/redesign-3'
    | '/dev/library/opus/redesign-1'
    | '/dev/library/opus/redesign-2'
    | '/dev/library/opus/redesign-3'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/settings'
    | '/signup'
    | '/verify-email'
    | '/dev/components'
    | '/dev/emails'
    | '/me/$conversationSessionId'
    | '/public-profile/$publicProfileId'
    | '/relationship/$analysisId'
    | '/today/calendar'
    | '/chat/'
    | '/circle/'
    | '/library/'
    | '/me/'
    | '/today/'
    | '/library/archetype/$slug'
    | '/library/facet/$slug'
    | '/library/guides/$slug'
    | '/library/science/$slug'
    | '/library/trait/$slug'
    | '/relationship/$analysisId_/ritual'
    | '/relationship/qr/$token'
    | '/today/week/$weekId'
    | '/dev/library/composer/redesign-1'
    | '/dev/library/composer/redesign-2'
    | '/dev/library/composer/redesign-3'
    | '/dev/library/direction/archetype'
    | '/dev/library/direction/facet'
    | '/dev/library/direction/trait'
    | '/dev/library/gpt/redesign-1'
    | '/dev/library/gpt/redesign-2'
    | '/dev/library/gpt/redesign-3'
    | '/dev/library/opus/redesign-1'
    | '/dev/library/opus/redesign-2'
    | '/dev/library/opus/redesign-3'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SettingsRoute: typeof SettingsRoute
  SignupRoute: typeof SignupRoute
  VerifyEmailRoute: typeof VerifyEmailRoute
  DevComponentsRoute: typeof DevComponentsRoute
  DevEmailsRoute: typeof DevEmailsRoute
  MeConversationSessionIdRoute: typeof MeConversationSessionIdRoute
  PublicProfilePublicProfileIdRoute: typeof PublicProfilePublicProfileIdRoute
  RelationshipAnalysisIdRoute: typeof RelationshipAnalysisIdRoute
  TodayCalendarRoute: typeof TodayCalendarRoute
  ChatIndexRoute: typeof ChatIndexRoute
  CircleIndexRoute: typeof CircleIndexRoute
  LibraryIndexRoute: typeof LibraryIndexRoute
  MeIndexRoute: typeof MeIndexRoute
  TodayIndexRoute: typeof TodayIndexRoute
  LibraryArchetypeSlugRoute: typeof LibraryArchetypeSlugRoute
  LibraryFacetSlugRoute: typeof LibraryFacetSlugRoute
  LibraryGuidesSlugRoute: typeof LibraryGuidesSlugRoute
  LibraryScienceSlugRoute: typeof LibraryScienceSlugRoute
  LibraryTraitSlugRoute: typeof LibraryTraitSlugRoute
  RelationshipAnalysisIdRitualRoute: typeof RelationshipAnalysisIdRitualRoute
  RelationshipQrTokenRoute: typeof RelationshipQrTokenRoute
  TodayWeekWeekIdRoute: typeof TodayWeekWeekIdRoute
  DevLibraryComposerRedesign1Route: typeof DevLibraryComposerRedesign1Route
  DevLibraryComposerRedesign2Route: typeof DevLibraryComposerRedesign2Route
  DevLibraryComposerRedesign3Route: typeof DevLibraryComposerRedesign3Route
  DevLibraryDirectionArchetypeRoute: typeof DevLibraryDirectionArchetypeRoute
  DevLibraryDirectionFacetRoute: typeof DevLibraryDirectionFacetRoute
  DevLibraryDirectionTraitRoute: typeof DevLibraryDirectionTraitRoute
  DevLibraryGptRedesign1Route: typeof DevLibraryGptRedesign1Route
  DevLibraryGptRedesign2Route: typeof DevLibraryGptRedesign2Route
  DevLibraryGptRedesign3Route: typeof DevLibraryGptRedesign3Route
  DevLibraryOpusRedesign1Route: typeof DevLibraryOpusRedesign1Route
  DevLibraryOpusRedesign2Route: typeof DevLibraryOpusRedesign2Route
  DevLibraryOpusRedesign3Route: typeof DevLibraryOpusRedesign3Route
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/verify-email': {
      id: '/verify-email'
      path: '/verify-email'
      fullPath: '/verify-email'
      preLoaderRoute: typeof VerifyEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/today/': {
      id: '/today/'
      path: '/today'
      fullPath: '/today/'
      preLoaderRoute: typeof TodayIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/me/': {
      id: '/me/'
      path: '/me'
      fullPath: '/me/'
      preLoaderRoute: typeof MeIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/library/': {
      id: '/library/'
      path: '/library'
      fullPath: '/library/'
      preLoaderRoute: typeof LibraryIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/circle/': {
      id: '/circle/'
      path: '/circle'
      fullPath: '/circle/'
      preLoaderRoute: typeof CircleIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat/': {
      id: '/chat/'
      path: '/chat'
      fullPath: '/chat/'
      preLoaderRoute: typeof ChatIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/today/calendar': {
      id: '/today/calendar'
      path: '/today/calendar'
      fullPath: '/today/calendar'
      preLoaderRoute: typeof TodayCalendarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/relationship/$analysisId': {
      id: '/relationship/$analysisId'
      path: '/relationship/$analysisId'
      fullPath: '/relationship/$analysisId'
      preLoaderRoute: typeof RelationshipAnalysisIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/public-profile/$publicProfileId': {
      id: '/public-profile/$publicProfileId'
      path: '/public-profile/$publicProfileId'
      fullPath: '/public-profile/$publicProfileId'
      preLoaderRoute: typeof PublicProfilePublicProfileIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/me/$conversationSessionId': {
      id: '/me/$conversationSessionId'
      path: '/me/$conversationSessionId'
      fullPath: '/me/$conversationSessionId'
      preLoaderRoute: typeof MeConversationSessionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dev/emails': {
      id: '/dev/emails'
      path: '/dev/emails'
      fullPath: '/dev/emails'
      preLoaderRoute: typeof DevEmailsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dev/components': {
      id: '/dev/components'
      path: '/dev/components'
      fullPath: '/dev/components'
      preLoaderRoute: typeof DevComponentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/today/week/$weekId': {
      id: '/today/week/$weekId'
      path: '/today/week/$weekId'
      fullPath: '/today/week/$weekId'
      preLoaderRoute: typeof TodayWeekWeekIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/relationship/qr/$token': {
      id: '/relationship/qr/$token'
      path: '/relationship/qr/$token'
      fullPath: '/relationship/qr/$token'
      preLoaderRoute: typeof RelationshipQrTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/relationship/$analysisId_/ritual': {
      id: '/relationship/$analysisId_/ritual'
      path: '/relationship/$analysisId/ritual'
      fullPath: '/relationship/$analysisId/ritual'
      preLoaderRoute: typeof RelationshipAnalysisIdRitualRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/library/trait/$slug': {
      id: '/library/trait/$slug'
      path: '/library/trait/$slug'
      fullPath: '/library/trait/$slug'
      preLoaderRoute: typeof LibraryTraitSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/library/science/$slug': {
      id: '/library/science/$slug'
      path: '/library/science/$slug'
      fullPath: '/library/science/$slug'
      preLoaderRoute: typeof LibraryScienceSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/library/guides/$slug': {
      id: '/library/guides/$slug'
      path: '/library/guides/$slug'
      fullPath: '/library/guides/$slug'
      preLoaderRoute: typeof LibraryGuidesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/library/facet/$slug': {
      id: '/library/facet/$slug'
      path: '/library/facet/$slug'
      fullPath: '/library/facet/$slug'
      preLoaderRoute: typeof LibraryFacetSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/library/archetype/$slug': {
      id: '/library/archetype/$slug'
      path: '/library/archetype/$slug'
      fullPath: '/library/archetype/$slug'
      preLoaderRoute: typeof LibraryArchetypeSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dev/library/opus/redesign-3': {
      id: '/dev/library/opus/redesign-3'
      path: '/dev/library/opus/redesign-3'
      fullPath: '/dev/library/opus/redesign-3'
      preLoaderRoute: typeof DevLibraryOpusRedesign3RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dev/library/opus/redesign-2': {
      id: '/dev/library/opus/redesign-2'
      path: '/dev/library/opus/redesign-2'
      fullPath: '/dev/library/opus/redesign-2'
      preLoaderRoute: typeof DevLibraryOpusRedesign2RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dev/library/opus/redesign-1': {
      id: '/dev/library/opus/redesign-1'
      path: '/dev/library/opus/redesign-1'
      fullPath: '/dev/library/opus/redesign-1'
      preLoaderRoute: typeof DevLibraryOpusRedesign1RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dev/library/gpt/redesign-3': {
      id: '/dev/library/gpt/redesign-3'
      path: '/dev/library/gpt/redesign-3'
      fullPath: '/dev/library/gpt/redesign-3'
      preLoaderRoute: typeof DevLibraryGptRedesign3RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dev/library/gpt/redesign-2': {
      id: '/dev/library/gpt/redesign-2'
      path: '/dev/library/gpt/redesign-2'
      fullPath: '/dev/library/gpt/redesign-2'
      preLoaderRoute: typeof DevLibraryGptRedesign2RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dev/library/gpt/redesign-1': {
      id: '/dev/library/gpt/redesign-1'
      path: '/dev/library/gpt/redesign-1'
      fullPath: '/dev/library/gpt/redesign-1'
      preLoaderRoute: typeof DevLibraryGptRedesign1RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dev/library/direction/trait': {
      id: '/dev/library/direction/trait'
      path: '/dev/library/direction/trait'
      fullPath: '/dev/library/direction/trait'
      preLoaderRoute: typeof DevLibraryDirectionTraitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dev/library/direction/facet': {
      id: '/dev/library/direction/facet'
      path: '/dev/library/direction/facet'
      fullPath: '/dev/library/direction/facet'
      preLoaderRoute: typeof DevLibraryDirectionFacetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dev/library/direction/archetype': {
      id: '/dev/library/direction/archetype'
      path: '/dev/library/direction/archetype'
      fullPath: '/dev/library/direction/archetype'
      preLoaderRoute: typeof DevLibraryDirectionArchetypeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dev/library/composer/redesign-3': {
      id: '/dev/library/composer/redesign-3'
      path: '/dev/library/composer/redesign-3'
      fullPath: '/dev/library/composer/redesign-3'
      preLoaderRoute: typeof DevLibraryComposerRedesign3RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dev/library/composer/redesign-2': {
      id: '/dev/library/composer/redesign-2'
      path: '/dev/library/composer/redesign-2'
      fullPath: '/dev/library/composer/redesign-2'
      preLoaderRoute: typeof DevLibraryComposerRedesign2RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dev/library/composer/redesign-1': {
      id: '/dev/library/composer/redesign-1'
      path: '/dev/library/composer/redesign-1'
      fullPath: '/dev/library/composer/redesign-1'
      preLoaderRoute: typeof DevLibraryComposerRedesign1RouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SettingsRoute: SettingsRoute,
  SignupRoute: SignupRoute,
  VerifyEmailRoute: VerifyEmailRoute,
  DevComponentsRoute: DevComponentsRoute,
  DevEmailsRoute: DevEmailsRoute,
  MeConversationSessionIdRoute: MeConversationSessionIdRoute,
  PublicProfilePublicProfileIdRoute: PublicProfilePublicProfileIdRoute,
  RelationshipAnalysisIdRoute: RelationshipAnalysisIdRoute,
  TodayCalendarRoute: TodayCalendarRoute,
  ChatIndexRoute: ChatIndexRoute,
  CircleIndexRoute: CircleIndexRoute,
  LibraryIndexRoute: LibraryIndexRoute,
  MeIndexRoute: MeIndexRoute,
  TodayIndexRoute: TodayIndexRoute,
  LibraryArchetypeSlugRoute: LibraryArchetypeSlugRoute,
  LibraryFacetSlugRoute: LibraryFacetSlugRoute,
  LibraryGuidesSlugRoute: LibraryGuidesSlugRoute,
  LibraryScienceSlugRoute: LibraryScienceSlugRoute,
  LibraryTraitSlugRoute: LibraryTraitSlugRoute,
  RelationshipAnalysisIdRitualRoute: RelationshipAnalysisIdRitualRoute,
  RelationshipQrTokenRoute: RelationshipQrTokenRoute,
  TodayWeekWeekIdRoute: TodayWeekWeekIdRoute,
  DevLibraryComposerRedesign1Route: DevLibraryComposerRedesign1Route,
  DevLibraryComposerRedesign2Route: DevLibraryComposerRedesign2Route,
  DevLibraryComposerRedesign3Route: DevLibraryComposerRedesign3Route,
  DevLibraryDirectionArchetypeRoute: DevLibraryDirectionArchetypeRoute,
  DevLibraryDirectionFacetRoute: DevLibraryDirectionFacetRoute,
  DevLibraryDirectionTraitRoute: DevLibraryDirectionTraitRoute,
  DevLibraryGptRedesign1Route: DevLibraryGptRedesign1Route,
  DevLibraryGptRedesign2Route: DevLibraryGptRedesign2Route,
  DevLibraryGptRedesign3Route: DevLibraryGptRedesign3Route,
  DevLibraryOpusRedesign1Route: DevLibraryOpusRedesign1Route,
  DevLibraryOpusRedesign2Route: DevLibraryOpusRedesign2Route,
  DevLibraryOpusRedesign3Route: DevLibraryOpusRedesign3Route,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
