import type { FacetName } from "@workspace/domain";
import type { LibraryReadingChapter } from "@/components/library/LibraryReadingRail";

const POLES: LibraryReadingChapter = { id: "facet-poles", label: "Across the scale" };
const SIBLING: LibraryReadingChapter = { id: "sibling-facet-map", label: "Sibling facets" };

export const FACET_READING_CHAPTERS: Partial<Record<FacetName, readonly LibraryReadingChapter[]>> =
	{
		achievement_striving: [
			{ id: "facet-poles", label: "Across the scale" },
			{ id: "sibling-facet-map", label: "Sibling facets" },
			{ id: "what-achievement-striving-measures", label: "What achievement striving measures" },
			{ id: "when-striving-is-more-relaxed", label: "When striving is more relaxed" },
			{ id: "when-striving-is-intense", label: "When striving is intense" },
			{ id: "how-it-shows-up-in-daily-life", label: "How it shows up in daily life" },
		],
		activity_level: [
			{ id: "facet-poles", label: "Across the scale" },
			{ id: "sibling-facet-map", label: "Sibling facets" },
			{ id: "what-activity-level-measures", label: "What activity level measures" },
			{ id: "when-activity-level-is-lower", label: "When activity level is lower" },
			{ id: "when-activity-level-is-higher", label: "When activity level is higher" },
			{ id: "how-it-shows-up-in-daily-life", label: "How it shows up in daily life" },
		],
		adventurousness: [
			{ id: "facet-poles", label: "Across the scale" },
			{ id: "sibling-facet-map", label: "Sibling facets" },
			{ id: "what-adventurousness-measures", label: "What adventurousness measures" },
			{ id: "when-adventurousness-is-lower", label: "When adventurousness is lower" },
			{ id: "when-adventurousness-is-higher", label: "When adventurousness is higher" },
			{ id: "how-it-shows-up-in-daily-life", label: "How it shows up in daily life" },
		],
		altruism: [
			{ id: "facet-poles", label: "Across the scale" },
			{ id: "sibling-facet-map", label: "Sibling facets" },
			{ id: "what-altruism-measures", label: "What altruism measures" },
			{ id: "when-altruism-is-more-selective", label: "When altruism is more selective" },
			{ id: "when-altruism-flows-freely", label: "When altruism flows freely" },
			{ id: "how-it-shows-up-in-daily-life", label: "How it shows up in daily life" },
		],
		anger: [
			{ id: "facet-poles", label: "Across the scale" },
			{ id: "sibling-facet-map", label: "Sibling facets" },
			{ id: "what-anger-measures", label: "What anger measures" },
			{ id: "when-anger-is-slower-to-rise", label: "When anger is slower to rise" },
			{ id: "when-anger-flares-faster", label: "When anger flares faster" },
			{ id: "how-it-shows-up-in-daily-life", label: "How it shows up in daily life" },
		],
		anxiety: [
			{ id: "facet-poles", label: "Across the scale" },
			{ id: "sibling-facet-map", label: "Sibling facets" },
			{ id: "what-anxiety-measures", label: "What anxiety measures" },
			{ id: "when-anxiety-is-lower", label: "When anxiety is lower" },
			{ id: "when-anxiety-is-higher", label: "When anxiety is higher" },
			{ id: "how-it-shows-up-in-daily-life", label: "How it shows up in daily life" },
		],
		artistic_interests: [
			{ id: "facet-poles", label: "Across the scale" },
			{ id: "sibling-facet-map", label: "Sibling facets" },
			{ id: "what-artistic-interests-measures", label: "What artistic interests measures" },
			{ id: "when-aesthetic-sensitivity-is-lower", label: "When aesthetic sensitivity is lower" },
			{ id: "when-aesthetic-sensitivity-is-higher", label: "When aesthetic sensitivity is higher" },
			{ id: "how-it-shows-up-in-daily-life", label: "How it shows up in daily life" },
		],
		assertiveness: [
			{ id: "facet-poles", label: "Across the scale" },
			{ id: "sibling-facet-map", label: "Sibling facets" },
			{ id: "what-assertiveness-measures", label: "What assertiveness measures" },
			{ id: "when-assertiveness-is-quieter", label: "When assertiveness is quieter" },
			{ id: "when-assertiveness-is-stronger", label: "When assertiveness is stronger" },
			{ id: "how-it-shows-up-in-daily-life", label: "How it shows up in daily life" },
		],
		cautiousness: [
			{ id: "facet-poles", label: "Across the scale" },
			{ id: "sibling-facet-map", label: "Sibling facets" },
			{ id: "what-cautiousness-measures", label: "What cautiousness measures" },
			{ id: "when-cautiousness-is-lower", label: "When cautiousness is lower" },
			{ id: "when-cautiousness-is-higher", label: "When cautiousness is higher" },
			{ id: "how-it-shows-up-in-daily-life", label: "How it shows up in daily life" },
		],
		cheerfulness: [
			{ id: "facet-poles", label: "Across the scale" },
			{ id: "sibling-facet-map", label: "Sibling facets" },
			{ id: "what-cheerfulness-measures", label: "What cheerfulness measures" },
			{ id: "when-cheerfulness-is-quieter", label: "When cheerfulness is quieter" },
			{ id: "when-cheerfulness-is-vivid", label: "When cheerfulness is vivid" },
			{ id: "how-it-shows-up-in-daily-life", label: "How it shows up in daily life" },
		],
		cooperation: [
			{ id: "facet-poles", label: "Across the scale" },
			{ id: "sibling-facet-map", label: "Sibling facets" },
			{ id: "what-cooperation-measures", label: "What cooperation measures" },
			{
				id: "when-cooperation-is-more-confrontational",
				label: "When cooperation is more confrontational",
			},
			{ id: "when-cooperation-is-stronger", label: "When cooperation is stronger" },
			{ id: "how-it-shows-up-in-daily-life", label: "How it shows up in daily life" },
		],
		depression: [
			{ id: "facet-poles", label: "Across the scale" },
			{ id: "sibling-facet-map", label: "Sibling facets" },
			{ id: "what-depression-measures", label: "What depression measures" },
			{ id: "when-depression-is-lower", label: "When depression is lower" },
			{ id: "when-depression-is-higher", label: "When depression is higher" },
			{ id: "how-it-shows-up-in-daily-life", label: "How it shows up in daily life" },
		],
		dutifulness: [
			{ id: "facet-poles", label: "Across the scale" },
			{ id: "sibling-facet-map", label: "Sibling facets" },
			{ id: "what-dutifulness-measures", label: "What dutifulness measures" },
			{ id: "when-dutifulness-is-more-independent", label: "When dutifulness is more independent" },
			{ id: "when-dutifulness-is-strong", label: "When dutifulness is strong" },
			{ id: "how-it-shows-up-in-daily-life", label: "How it shows up in daily life" },
		],
		emotionality: [
			{ id: "facet-poles", label: "Across the scale" },
			{ id: "sibling-facet-map", label: "Sibling facets" },
			{ id: "what-emotionality-measures", label: "What emotionality measures" },
			{ id: "when-emotionality-is-quieter", label: "When emotionality is quieter" },
			{ id: "when-emotionality-is-more-open", label: "When emotionality is more open" },
			{ id: "how-it-shows-up-in-daily-life", label: "How it shows up in daily life" },
		],
		excitement_seeking: [
			{ id: "facet-poles", label: "Across the scale" },
			{ id: "sibling-facet-map", label: "Sibling facets" },
			{ id: "what-excitement-seeking-measures", label: "What excitement seeking measures" },
			{ id: "when-excitement-seeking-is-lower", label: "When excitement seeking is lower" },
			{ id: "when-excitement-seeking-is-higher", label: "When excitement seeking is higher" },
			{ id: "how-it-shows-up-in-daily-life", label: "How it shows up in daily life" },
		],
		friendliness: [
			{ id: "facet-poles", label: "Across the scale" },
			{ id: "sibling-facet-map", label: "Sibling facets" },
			{ id: "what-friendliness-measures", label: "What friendliness measures" },
			{ id: "when-friendliness-is-more-reserved", label: "When friendliness is more reserved" },
			{ id: "when-friendliness-comes-easily", label: "When friendliness comes easily" },
			{ id: "how-it-shows-up-in-daily-life", label: "How it shows up in daily life" },
		],
		gregariousness: [
			{ id: "facet-poles", label: "Across the scale" },
			{ id: "sibling-facet-map", label: "Sibling facets" },
			{ id: "what-gregariousness-measures", label: "What gregariousness measures" },
			{ id: "when-gregariousness-is-lower", label: "When gregariousness is lower" },
			{ id: "when-gregariousness-is-higher", label: "When gregariousness is higher" },
			{ id: "how-it-shows-up-in-daily-life", label: "How it shows up in daily life" },
		],
		imagination: [
			{ id: "facet-poles", label: "Across the scale" },
			{ id: "sibling-facet-map", label: "Sibling facets" },
			{ id: "what-imagination-measures", label: "What imagination measures" },
			{ id: "when-imagination-is-quieter", label: "When imagination is quieter" },
			{ id: "when-imagination-is-vivid", label: "When imagination is vivid" },
			{ id: "how-it-shows-up-in-daily-life", label: "How it shows up in daily life" },
		],
		immoderation: [
			{ id: "facet-poles", label: "Across the scale" },
			{ id: "sibling-facet-map", label: "Sibling facets" },
			{ id: "what-immoderation-measures", label: "What immoderation measures" },
			{ id: "when-immoderation-is-lower", label: "When immoderation is lower" },
			{ id: "when-immoderation-is-higher", label: "When immoderation is higher" },
			{ id: "how-it-shows-up-in-daily-life", label: "How it shows up in daily life" },
		],
		intellect: [
			{ id: "facet-poles", label: "Across the scale" },
			{ id: "sibling-facet-map", label: "Sibling facets" },
			{ id: "what-intellect-measures", label: "What intellect measures" },
			{
				id: "when-intellectual-curiosity-is-more-focused",
				label: "When intellectual curiosity is more focused",
			},
			{ id: "when-intellectual-curiosity-is-broad", label: "When intellectual curiosity is broad" },
			{ id: "how-it-shows-up-in-daily-life", label: "How it shows up in daily life" },
		],
		liberalism: [
			{ id: "facet-poles", label: "Across the scale" },
			{ id: "sibling-facet-map", label: "Sibling facets" },
			{ id: "what-liberalism-measures", label: "What liberalism measures" },
			{ id: "when-convention-is-valued", label: "When convention is valued" },
			{ id: "when-re-examination-comes-naturally", label: "When re-examination comes naturally" },
			{ id: "how-it-shows-up-in-daily-life", label: "How it shows up in daily life" },
		],
		modesty: [
			{ id: "facet-poles", label: "Across the scale" },
			{ id: "sibling-facet-map", label: "Sibling facets" },
			{ id: "what-modesty-measures", label: "What modesty measures" },
			{ id: "when-modesty-is-lower", label: "When modesty is lower" },
			{ id: "when-modesty-is-higher", label: "When modesty is higher" },
			{ id: "how-it-shows-up-in-daily-life", label: "How it shows up in daily life" },
		],
		morality: [
			{ id: "facet-poles", label: "Across the scale" },
			{ id: "sibling-facet-map", label: "Sibling facets" },
			{ id: "what-morality-measures", label: "What morality measures" },
			{ id: "when-morality-is-more-strategic", label: "When morality is more strategic" },
			{ id: "when-morality-is-direct", label: "When morality is direct" },
			{ id: "how-it-shows-up-in-daily-life", label: "How it shows up in daily life" },
		],
		orderliness: [
			{ id: "facet-poles", label: "Across the scale" },
			{ id: "sibling-facet-map", label: "Sibling facets" },
			{ id: "what-orderliness-measures", label: "What orderliness measures" },
			{ id: "when-orderliness-is-more-relaxed", label: "When orderliness is more relaxed" },
			{ id: "when-orderliness-is-strong", label: "When orderliness is strong" },
			{ id: "how-it-shows-up-in-daily-life", label: "How it shows up in daily life" },
		],
		self_consciousness: [
			{ id: "facet-poles", label: "Across the scale" },
			{ id: "sibling-facet-map", label: "Sibling facets" },
			{ id: "what-self-consciousness-measures", label: "What self-consciousness measures" },
			{ id: "when-self-consciousness-is-lower", label: "When self-consciousness is lower" },
			{ id: "when-self-consciousness-is-higher", label: "When self-consciousness is higher" },
			{ id: "how-it-shows-up-in-daily-life", label: "How it shows up in daily life" },
		],
		self_discipline: [
			{ id: "facet-poles", label: "Across the scale" },
			{ id: "sibling-facet-map", label: "Sibling facets" },
			{ id: "what-self-discipline-measures", label: "What self-discipline measures" },
			{ id: "when-self-discipline-is-more-fluid", label: "When self-discipline is more fluid" },
			{ id: "when-self-discipline-is-strong", label: "When self-discipline is strong" },
			{ id: "how-it-shows-up-in-daily-life", label: "How it shows up in daily life" },
		],
		self_efficacy: [
			{ id: "facet-poles", label: "Across the scale" },
			{ id: "sibling-facet-map", label: "Sibling facets" },
			{ id: "what-self-efficacy-measures", label: "What self-efficacy measures" },
			{ id: "when-self-efficacy-is-more-cautious", label: "When self-efficacy is more cautious" },
			{ id: "when-self-efficacy-is-strong", label: "When self-efficacy is strong" },
			{ id: "how-it-shows-up-in-daily-life", label: "How it shows up in daily life" },
		],
		sympathy: [
			{ id: "facet-poles", label: "Across the scale" },
			{ id: "sibling-facet-map", label: "Sibling facets" },
			{ id: "what-sympathy-measures", label: "What sympathy measures" },
			{ id: "when-sympathy-is-more-analytical", label: "When sympathy is more analytical" },
			{ id: "when-sympathy-is-strong", label: "When sympathy is strong" },
			{ id: "how-it-shows-up-in-daily-life", label: "How it shows up in daily life" },
		],
		trust: [
			{ id: "facet-poles", label: "Across the scale" },
			{ id: "sibling-facet-map", label: "Sibling facets" },
			{ id: "what-trust-measures", label: "What trust measures" },
			{ id: "when-trust-is-more-guarded", label: "When trust is more guarded" },
			{ id: "when-trust-comes-readily", label: "When trust comes readily" },
			{ id: "how-it-shows-up-in-daily-life", label: "How it shows up in daily life" },
		],
		vulnerability: [
			{ id: "facet-poles", label: "Across the scale" },
			{ id: "sibling-facet-map", label: "Sibling facets" },
			{ id: "what-vulnerability-measures", label: "What vulnerability measures" },
			{ id: "when-vulnerability-is-lower", label: "When vulnerability is lower" },
			{ id: "when-vulnerability-is-higher", label: "When vulnerability is higher" },
			{ id: "how-it-shows-up-in-daily-life", label: "How it shows up in daily life" },
		],
	};

export function getFacetReadingChapters(facet: FacetName): readonly LibraryReadingChapter[] {
	const list = FACET_READING_CHAPTERS[facet];
	if (list) return list;
	return [POLES, SIBLING];
}
