name: agent-team-pipeline
description: "Orchestrate full story pipeline with agent teams and worktree isolation — from story creation through PR"
author: "BMad"

# Critical variables from config
config_source: "{project-root}/_bmad/bmm/config.yaml"
output_folder: "{config_source}:output_folder"
user_name: "{config_source}:user_name"
communication_language: "{config_source}:communication_language"
user_skill_level: "{config_source}:user_skill_level"
document_output_language: "{config_source}:document_output_language"
story_dir: "{config_source}:implementation_artifacts"
date: system-generated

# Workflow components
installed_path: "{project-root}/_bmad/bmm/workflows/4-implementation/agent-team-pipeline"
instructions: "{installed_path}/instructions.xml"
validation: "{installed_path}/checklist.md"
reference_doc: "{installed_path}/workflow.md"

# Variables and inputs
story_file: "" # Explicit story path; auto-discovered if empty
implementation_artifacts: "{config_source}:implementation_artifacts"
planning_artifacts: "{config_source}:planning_artifacts"
sprint_status: "{implementation_artifacts}/sprint-status.yaml"
project_context: "**/project-context.md"

variables:
  sprint_status: "{implementation_artifacts}/sprint-status.yaml"
  epics_file: "{planning_artifacts}/epics.md"
  team_name: "" # Auto-generated from story key if empty
  max_typecheck_retries: 3
  max_e2e_retries: 3
